model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False # for debugging
  prompt_template: '[INST] {} [/INST]'
  llama_model: "llama2/Llama-2-7b-chat-hf"
  ckpt: "MiniGPT-Med/pretrained/miniGPT_Med.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  diff_vqa:
    ann_path: /data/mimic-cxr-jpg-2.1.0/
    vis_root: ./pretrained_img_features/mae_224_sam_1024
    max_new_tokens: 300
    batch_size: 2
    text_processor:
        name: "blip_caption"

run:
  task: image_text_pretrain
  name: diff_vqa_eval
  save_path: ./MiniGPT-Med/experiments