datasets:
  detect_mimic:
    data_type: images
    build_info:
      image_path: /miniGPT-Med/mimic-cxr-dataset/detection_MIMIC
      ann_path: /miniGPT-Med/json_files/MIMIC-bbox/train_detect_mimic.json